sudo: required
services:
  - docker

before_install:
  - docker build -t danielrejniak/nginx-vuejs .

script:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push danielrejniak/nginx-vuejs
  